/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral./*domain_area*/;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for /*operator_class_name_area*/
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class /*operator_class_name_area*/OpTest extends BaseIndexOpTest</*operator_class_name_area*/Op> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{/*operator_bands_names_area*/}, /*operator_product_width_area*/, /*operator_product_height_area*/, new float[]{/*operator_bands_wavelengths_area*/}, new float[]{/*operator_bands_min_values_area*/}, new float[]{/*operator_bands_max_values_area*/});
        setOperatorParameters(new HashMap<>()/*operator_parameters_map_area*/);
        setTargetValues(new float[]{
                /*operator_target_values_area*/});
    }
}
