package eu.esa.opt.spectral.vegetation;

import com.bc.ceres.core.ProgressMonitor;
import eu.esa.opt.radiometry.BaseIndexOp;
import eu.esa.opt.radiometry.annotations.BandParameter;
import org.esa.snap.core.datamodel.Band;
import org.esa.snap.core.gpf.OperatorException;
import org.esa.snap.core.gpf.OperatorSpi;
import org.esa.snap.core.gpf.Tile;
import org.esa.snap.core.gpf.annotations.OperatorMetadata;
import org.esa.snap.core.gpf.annotations.Parameter;

import java.awt.*;
import java.util.Map;

/**
 * Operator class for Mmsr705
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsClassesGenerator
 *
 * @author Adrian Draghici
 */
@OperatorMetadata(
        alias = "Mmsr705Op",
        version = "1.0",
        category = "Optical/Thematic Land Processing/Vegetation Spectral Indices",
        description = "Modified Simple Ratio (705 and 445 nm)",
        authors = "Adrian Draghici",
        copyright = "Copyright (C) 2025 by CS Group ROMANIA")
public class Mmsr705Op extends BaseIndexOp {

    // constants
    public static final String BAND_NAME = "mmsr705";

    @Parameter(label = "Aerosols source band",
            description = "The Aerosols band for the Template computation. If not provided, the operator will try to find the best fitting band.",
            rasterDataNodeType = Band.class)
    @BandParameter(minWavelength = 400, maxWavelength = 455)
    private String aerosolsSourceBand;

    @Parameter(label = "Red edge 2 source band",
            description = "The Red Edge 2 band for the Template computation. If not provided, the operator will try to find the best fitting band.",
            rasterDataNodeType = Band.class)
    @BandParameter(minWavelength = 730, maxWavelength = 750)
    private String redEdge2SourceBand;

    @Override
    public String getBandName() {
        return BAND_NAME;
    }

    @Override
    public void computeTileStack(Map<Band, Tile> targetTiles, Rectangle rectangle, ProgressMonitor pm) throws OperatorException {
        pm.beginTask("Computing Mmsr705", rectangle.height);
        try {

            Tile aerosolsTile = getSourceTile(getSourceProduct().getBand(aerosolsSourceBand), rectangle);
            Tile redEdge2Tile = getSourceTile(getSourceProduct().getBand(redEdge2SourceBand), rectangle);

            // SIITBX-494 - retrieve bands after suffix (which is the operator band name)
            Tile mmsr705 = targetTiles.get(getBandWithSuffix(targetProduct, "_" + BAND_NAME));
            Tile mmsr705Flags = targetTiles.get(targetProduct.getBand(FLAGS_BAND_NAME));

            float mmsr705Value;

            for (int y = rectangle.y; y < rectangle.y + rectangle.height; y++) {
                for (int x = rectangle.x; x < rectangle.x + rectangle.width; x++) {

                    final float a = aerosolsTile.getSampleFloat(x, y);
                    final float re2 = redEdge2Tile.getSampleFloat(x, y);

                    mmsr705Value = (re2 - a) / (re2 + a);
                    mmsr705.setSample(x, y, computeFlag(x, y, mmsr705Value, mmsr705Flags));
                }
                checkForCancellation();
                pm.worked(1);
            }
        } finally {
            pm.done();
        }
    }

    public static class Spi extends OperatorSpi {

        public Spi() {
            super(Mmsr705Op.class);
        }
    }
}
