/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.soil;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Ndbai
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class NdbaiOpTest extends BaseIndexOpTest<NdbaiOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"swir1", "thermal"}, 3, 3, new float[]{1550, 10400}, new float[]{0.004760504f, 0.1685574f}, new float[]{0.28437048f, 0.9511195f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                -0.9450662f, -0.7405219f, -0.65974194f, -0.61648697f, -0.5895381f, -0.57113713f, -0.55777377f, -0.5476284f, -0.5396636f});
    }
}
