/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.burn;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Baim
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class BaimOpTest extends BaseIndexOpTest<BaimOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"nir", "swir2"}, 3, 3, new float[]{760, 2130}, new float[]{0.24048835f, 0.10579318f}, new float[]{0.7328311f, 0.48590213f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                27.567854f, 15.745323f, 10.169975f, 7.1090164f, 5.2538033f, 4.0494676f, 3.2281098f, 2.6475086f, 2.226474f});
    }
}
