/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.burn;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Bais2
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class Bais2OpTest extends BaseIndexOpTest<Bais2Op> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"redEdge2", "redEdge3", "red", "nir2", "nir", "swir2"}, 3, 3, new float[]{730, 815, 670, 900, 760, 2130}, new float[]{0.35530716f, 0.122415066f, 0.428984f, 0.6948421f, 0.029857934f, 0.75668836f}, new float[]{0.7269573f, 0.68234885f, 0.62936914f, 0.8772204f, 0.16124105f, 0.9228676f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                1.9729419f, 1.9657083f, 1.9596066f, 1.9542964f, 1.9496121f, 1.9454572f, 1.9417696f, 1.9385058f, 1.9356344f});
    }
}
