/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.burn;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Nbrt2
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class Nbrt2OpTest extends BaseIndexOpTest<Nbrt2Op> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"nir", "swir2", "thermal"}, 3, 3, new float[]{760, 2130, 10400}, new float[]{0.4100721f, 0.5478846f, 0.017621756f}, new float[]{0.8519415f, 0.8397961f, 0.675106f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.9999953f, 0.99997485f, 0.99995655f, 0.9999396f, 0.9999239f, 0.99990875f, 0.9998944f, 0.9998804f, 0.9998669f});
    }
}
