/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.burn;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Ndvit
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class NdvitOpTest extends BaseIndexOpTest<NdvitOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"red", "nir", "thermal"}, 3, 3, new float[]{670, 760, 10400}, new float[]{0.31475943f, 0.09831625f, 0.8221494f}, new float[]{0.73007613f, 0.30851364f, 0.9936892f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.99947375f, 0.99950355f, 0.99952006f, 0.9995292f, 0.9995338f, 0.9995353f, 0.99953485f, 0.99953294f, 0.99952984f});
    }
}
