/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.burn;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Nstv1
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class Nstv1OpTest extends BaseIndexOpTest<Nstv1Op> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"nir", "swir2", "thermal"}, 3, 3, new float[]{760, 2130, 10400}, new float[]{0.07056552f, 0.2239492f, 0.035640836f}, new float[]{0.10481095f, 0.67629266f, 0.34069526f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                -0.018561795f, -0.04269464f, -0.06935057f, -0.0975644f, -0.12680754f, -0.15676624f, -0.18724252f, -0.21810523f, -0.24926412f});
    }
}
