/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.burn;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Savit
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class SavitOpTest extends BaseIndexOpTest<SavitOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"red", "nir", "thermal"}, 3, 3, new float[]{670, 760, 10400}, new float[]{0.42316258f, 0.30236703f, 0.19375825f}, new float[]{0.60037124f, 0.5624453f, 0.5135054f});
        setOperatorParameters(new HashMap<>() {{
                                  put("l", 0.33498448f);
                              }}
        );
        setTargetValues(new float[]{
                0.633307f, 0.66735387f, 0.69824827f, 0.7264087f, 0.7521825f, 0.77586067f, 0.7976887f, 0.81787544f, 0.836599f});
    }
}
