/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.urban;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Dbi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class DbiOpTest extends BaseIndexOpTest<DbiOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"blue", "red", "nir", "thermal1", "thermal"}, 3, 3, new float[]{450, 670, 760, 10650, 10400}, new float[]{0.37604553f, 0.16397142f, 0.26408386f, 0.09015483f, 0.25275254f}, new float[]{0.86727476f, 0.6458781f, 0.4487465f, 0.33854592f, 0.88695264f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.37935835f, 0.44297314f, 0.48894003f, 0.5237071f, 0.5509226f, 0.5728055f, 0.59078324f, 0.6058154f, 0.6185711f});
    }
}
