/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.urban;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Pisi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class PisiOpTest extends BaseIndexOpTest<PisiOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"blue", "nir"}, 3, 3, new float[]{450, 760}, new float[]{0.30027968f, 0.28594214f}, new float[]{0.8138396f, 0.44942886f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.15700129f, 0.19786988f, 0.23873848f, 0.27960706f, 0.32047564f, 0.36134416f, 0.40221274f, 0.44308138f, 0.48394996f});
    }
}
