/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Atsavi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class AtsaviOpTest extends BaseIndexOpTest<AtsaviOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"red", "nir"}, 3, 3, new float[]{670, 760}, new float[]{0.0774886f, 0.43878245f}, new float[]{0.19268459f, 0.9786376f});
        setOperatorParameters(new HashMap<>() {{
                                  put("l", 0.26670694f);
                                  put("sla", 0.94923055f);
                                  put("slb", 0.45882124f);
                              }}
        );
        setTargetValues(new float[]{
                -0.42194983f, -0.13065593f, 0.03625161f, 0.14442721f, 0.22023275f, 0.2763067f, 0.319466f, 0.35371134f, 0.381546f});
    }
}
