/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Bcc
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class BccOpTest extends BaseIndexOpTest<BccOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"blue", "green", "red"}, 3, 3, new float[]{450, 560, 670}, new float[]{0.61961097f, 0.66213757f, 0.6727695f}, new float[]{0.6476077f, 0.92530835f, 0.99856395f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.3170147f, 0.3067035f, 0.2971465f, 0.2882638f, 0.27998656f, 0.27225488f, 0.26501656f, 0.25822583f, 0.2518424f});
    }
}
