/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Cig
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class CigOpTest extends BaseIndexOpTest<CigOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"green", "nir"}, 3, 3, new float[]{560, 760}, new float[]{0.47122395f, 0.6457423f}, new float[]{0.7364258f, 0.6956945f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.3703512f, 0.2926638f, 0.22455907f, 0.16436636f, 0.1107831f, 0.06277692f, 0.019520283f, -0.019658089f, -0.055309474f});
    }
}
