/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Dswi5
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class Dswi5OpTest extends BaseIndexOpTest<Dswi5Op> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"green", "red", "nir", "swir1"}, 3, 3, new float[]{560, 670, 760, 1550}, new float[]{0.12640703f, 0.38515228f, 0.0052874684f, 0.057567775f}, new float[]{0.7167479f, 0.71404004f, 0.19056404f, 0.658396f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.29746675f, 0.40907592f, 0.48226216f, 0.5339531f, 0.5724061f, 0.6021292f, 0.62579226f, 0.6450771f, 0.661096f});
    }
}
