/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Gbndvi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class GbndviOpTest extends BaseIndexOpTest<GbndviOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"blue", "green", "nir"}, 3, 3, new float[]{450, 560, 760}, new float[]{0.19635767f, 0.30930632f, 0.8203534f}, new float[]{0.6026341f, 0.8002686f, 0.9773415f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.23731922f, 0.15239315f, 0.0815481f, 0.021550164f, -0.029914724f, -0.07454613f, -0.11362022f, -0.14811425f, -0.17878887f});
    }
}
