/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Gosavi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class GosaviOpTest extends BaseIndexOpTest<GosaviOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"green", "nir"}, 3, 3, new float[]{560, 760}, new float[]{0.104439795f, 0.505213f}, new float[]{0.7806567f, 0.78082854f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.52071947f, 0.39464948f, 0.29835215f, 0.22239475f, 0.16094853f, 0.110217705f, 0.0676241f, 0.031355307f, 9.982089E-5f});
    }
}
