/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Gsavi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class GsaviOpTest extends BaseIndexOpTest<GsaviOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"green", "nir"}, 3, 3, new float[]{560, 760}, new float[]{0.8602329f, 0.36987972f}, new float[]{0.99778295f, 0.5779052f});
        setOperatorParameters(new HashMap<>() {{
                                  put("l", 0.30070293f);
                              }}
        );
        setTargetValues(new float[]{
                -0.41664314f, -0.3979291f, -0.38021478f, -0.3634222f, -0.34748113f, -0.33232853f, -0.31790727f, -0.30416566f, -0.29105675f});
    }
}
