/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Mcariosavi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class McariosaviOpTest extends BaseIndexOpTest<McariosaviOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"green", "redEdge1", "red", "nir"}, 3, 3, new float[]{560, 695, 670, 760}, new float[]{0.13196701f, 0.3748113f, 0.32099015f, 0.71502376f}, new float[]{0.14660686f, 0.7050628f, 0.66977155f, 0.8427401f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.016047768f, -0.016702974f, -0.056852162f, -0.10664664f, -0.16910282f, -0.24846944f, -0.3510045f, -0.4863766f, -0.67040634f});
    }
}
