/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Mgrvi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class MgrviOpTest extends BaseIndexOpTest<MgrviOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"green", "red"}, 3, 3, new float[]{560, 670}, new float[]{0.15212631f, 0.22662467f}, new float[]{0.23746759f, 0.8854124f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                -0.37873676f, -0.56542295f, -0.6715568f, -0.73745304f, -0.7813564f, -0.8122612f, -0.83497775f, -0.85226333f, -0.86579126f});
    }
}
