/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Mmnd705
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class Mmnd705OpTest extends BaseIndexOpTest<Mmnd705Op> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"aerosols", "redEdge1", "redEdge2", "red"}, 3, 3, new float[]{470, 695, 730, 670}, new float[]{0.18443811f, 0.23392653f, 0.13164479f, 0.56831396f}, new float[]{0.78614396f, 0.47074848f, 0.7762253f, 0.8853517f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                -0.56467694f, -0.23745038f, -0.0013625214f, 0.17700793f, 0.31652147f, 0.42862797f, 0.52068096f, 0.59761983f, 0.6628843f});
    }
}
