/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Msi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class MsiOpTest extends BaseIndexOpTest<MsiOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"nir", "swir1"}, 3, 3, new float[]{760, 1550}, new float[]{0.006662607f, 0.14612812f}, new float[]{0.48261505f, 0.38269025f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                21.932573f, 2.6557927f, 1.6336448f, 1.2684069f, 1.0808145f, 0.9666152f, 0.88978475f, 0.8345602f, 0.79295135f});
    }
}
