/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Ndyi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class NdyiOpTest extends BaseIndexOpTest<NdyiOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"blue", "green"}, 3, 3, new float[]{450, 560}, new float[]{0.15757287f, 0.031647623f}, new float[]{0.5626493f, 0.54330325f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                -0.66549474f, -0.37063333f, -0.237284f, -0.16127363f, -0.112163626f, -0.07782075f, -0.052454863f, -0.032953124f, -0.017492667f});
    }
}
