/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Normnir
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class NormnirOpTest extends BaseIndexOpTest<NormnirOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"green", "red", "nir"}, 3, 3, new float[]{560, 670, 760}, new float[]{0.25375742f, 0.18314701f, 0.79232687f}, new float[]{0.5090878f, 0.22207797f, 0.84408414f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.644571f, 0.62774605f, 0.6120272f, 0.5973089f, 0.5834986f, 0.57051486f, 0.5582854f, 0.5467466f, 0.5358414f});
    }
}
