/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Nrfig
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class NrfigOpTest extends BaseIndexOpTest<NrfigOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"green", "swir2"}, 3, 3, new float[]{560, 2130}, new float[]{0.046985388f, 0.38034952f}, new float[]{0.9266625f, 0.91846f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                -0.7801004f, -0.48079446f, -0.3171889f, -0.2140516f, -0.14308812f, -0.09127475f, -0.051781315f, -0.020680705f, 0.0044455f});
    }
}
