/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Psri
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class PsriOpTest extends BaseIndexOpTest<PsriOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"blue", "redEdge2", "red"}, 3, 3, new float[]{450, 730, 670}, new float[]{0.050462723f, 0.10990435f, 0.22797811f}, new float[]{0.9687789f, 0.61182415f, 0.6767663f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                1.6151807f, 0.6882613f, 0.25546902f, 0.0048381593f, -0.158643f, -0.27369797f, -0.359068f, -0.42492867f, -0.47728196f});
    }
}
