/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Slavi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class SlaviOpTest extends BaseIndexOpTest<SlaviOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"red", "nir", "swir2"}, 3, 3, new float[]{670, 760, 2130}, new float[]{0.2881928f, 0.006698847f, 0.7415665f}, new float[]{0.63217545f, 0.06308001f, 0.8603834f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.006505255f, 0.012639183f, 0.018153539f, 0.023137683f, 0.027664576f, 0.03179438f, 0.035577152f, 0.03905487f, 0.042262997f});
    }
}
