/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Sr3
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class Sr3OpTest extends BaseIndexOpTest<Sr3Op> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"green", "redEdge1", "red", "nir"}, 3, 3, new float[]{560, 695, 670, 760}, new float[]{0.107497275f, 0.39038748f, 0.56629616f, 0.3265375f}, new float[]{0.5848029f, 0.8565555f, 0.6821214f, 0.9404451f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                2.5408134f, 2.1684787f, 2.0038836f, 1.9143335f, 1.8595172f, 1.8232703f, 1.7979475f, 1.7795082f, 1.7656387f});
    }
}
