/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Sr555
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class Sr555OpTest extends BaseIndexOpTest<Sr555Op> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"green", "redEdge2", "red"}, 3, 3, new float[]{560, 730, 670}, new float[]{0.045275867f, 0.27471912f, 0.4032787f}, new float[]{0.21307367f, 0.8573442f, 0.443456f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                6.0676723f, 5.2459497f, 4.8194194f, 4.558256f, 4.381906f, 4.254825f, 4.1588964f, 4.0839167f, 4.0236983f});
    }
}
