/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.vegetation;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Tcariosavi705
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class Tcariosavi705OpTest extends BaseIndexOpTest<Tcariosavi705Op> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"green", "redEdge1", "redEdge2", "red"}, 3, 3, new float[]{560, 695, 730, 670}, new float[]{0.3643114f, 0.09633982f, 0.44963986f, 0.5056421f}, new float[]{0.36940515f, 0.55385077f, 0.57219344f, 0.66223145f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                1.4141914f, 1.6217176f, 1.773982f, 1.8862777f, 1.9482104f, 1.9244523f, 1.7153904f, 0.93979144f, -4.2716784f});
    }
}
