/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.water;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Aweish
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class AweishOpTest extends BaseIndexOpTest<AweishOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"blue", "green", "nir", "swir1", "swir2"}, 3, 3, new float[]{450, 560, 760, 1550, 2130}, new float[]{0.091347754f, 0.21880907f, 0.2374165f, 0.096731484f, 0.10103613f}, new float[]{0.2365439f, 0.24369371f, 0.38208574f, 0.1769436f, 0.35256332f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                0.11188941f, 0.08778989f, 0.06369039f, 0.039590877f, 0.015491307f, -0.0086081475f, -0.032707594f, -0.05680716f, -0.080906674f});
    }
}
