/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.water;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Swm
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class SwmOpTest extends BaseIndexOpTest<SwmOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"blue", "green", "nir", "swir1"}, 3, 3, new float[]{450, 560, 760, 1550}, new float[]{0.057874918f, 0.7990688f, 0.11994308f, 0.35047036f}, new float[]{0.59419906f, 0.9655698f, 0.5524256f, 0.8894531f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                1.8216821f, 1.5963544f, 1.4477489f, 1.3423815f, 1.263778f, 1.20289f, 1.1543354f, 1.1147114f, 1.0817615f});
    }
}
