/*
 *
 *  * Copyright (C) 2025 CS GROUP ROMANIA
 *  *
 *  * This program is free software; you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published by the Free
 *  * Software Foundation; either version 3 of the License, or (at your option)
 *  * any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT
 *  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  * more details.
 *  *
 *  * You should have received a copy of the GNU General Public License along
 *  *  with this program; if not, see http://www.gnu.org/licenses/
 *
 */

package eu.esa.opt.spectral.water;

import eu.esa.opt.radiometry.BaseIndexOpTest;
import org.junit.Before;

import java.util.HashMap;

/**
 * Operator test class for Twi
 * Generated by @see eu.esa.opt.radiometry.util.RadiometricIndicesOpsTestClassesGenerator
 *
 * @author Adrian Draghici
 */
public class TwiOpTest extends BaseIndexOpTest<TwiOp> {

    @Before
    public void setUp() throws Exception {
        setupBands(new String[]{"blue", "green", "redEdge1", "redEdge2", "red", "nir", "swir2"}, 3, 3, new float[]{450, 560, 695, 730, 670, 760, 2130}, new float[]{0.7718683f, 0.4773419f, 0.16587478f, 0.6081445f, 0.05144018f, 0.076025665f, 0.45809972f}, new float[]{0.8068602f, 0.5550338f, 0.82675755f, 0.6656588f, 0.40954524f, 0.106032014f, 0.7777895f});
        setOperatorParameters(new HashMap<>());
        setTargetValues(new float[]{
                -0.65967846f, -0.38022697f, -0.1278199f, 0.1012764f, 0.31013983f, 0.5013295f, 0.67699194f, 0.83893955f, 0.98871434f});
    }
}
